spring:
  application:
    name: sensor-monitoring
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:sensor_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:your_password}
    hikari:
      maximum-pool-size: 30
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect


server:
  port: ${SERVER_PORT:8082}

logging:
  level:
    omc: trace


sensors:
  path:
    input: ${INPUT_PATH:/sensors/data}
  db:
    batch:
      size: ${BATCH_SIZE:25000}
      frequency: ${BATCH_FREQUENCY:2}
  temperature:
    acceptable:
      deviation: ${DEVIATION:0.2}
